<?php
session_start();
require_once("Config/connectDataBase.php");
require_once("Controller/indexController.php");
require_once("Controller/userController.php");
require_once("Controller/siteController.php");
require_once("Controller/SCPController.php");
require_once("Controller/scientistController.php");
require_once("Controller/guardController.php");
require_once("Controller/classDController.php");
require_once("Controller/experienceController.php");